name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  ZIG_VERSION: "0.14.0"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Zig
        uses: mlugg/setup-zig@v1.2.1
        with:
          version: ${{ env.ZIG_VERSION }}
      - name: Install Dependecies
        run: sudo apt-get install -y libglx-dev libxcursor-dev libxfixes-dev libxi-dev libxinerama-dev libxrandr-dev
      - name: Build
        run: zig build -Doptimize=ReleaseSafe
      - name: Create Artifact
        run: |
          mkdir folly
          mv zig-out/bin/folly folly/folly
          mv editor folly/editor
          mv resources folly/resources
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: folly-linux
          path: folly
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Zig
        uses: mlugg/setup-zig@v1.2.1
        with:
          version: ${{ env.ZIG_VERSION }}
      - name: Build
        run: zig build -Doptimize=ReleaseSafe
      - name: Create Artifact
        run: |
          New-Item -Path . -Name "folly" -ItemType "directory"
          Move-Item -Path .\zig-out\bin\folly.exe -Destination .\folly\folly.exe
          Move-Item -Path .\editor -Destination .\folly\editor
          Move-Item -Path .\resources -Destination .\folly\resources
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: folly-windows
          path: folly
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Zig
        uses: mlugg/setup-zig@v1.2.1
        with:
          version: ${{ env.ZIG_VERSION }}
      - name: Build
        run: zig build -Doptimize=ReleaseSafe
        env:
          AGREE: true
      - name: Create Artifact
        run: |
          mkdir folly
          mv zig-out/bin/folly folly/folly
          mv editor folly/editor
          mv resources folly/resources
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: folly-macos
          path: folly